#!/bin/bash

if [ -x /etc/init.d/artifactory ];
then
    # delegate to service
    /etc/init.d/artifactory "$@"
else
    # call artifactory.sh
    artBinDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    $artBinDir/artifactory.sh "$@"
fi